<?php
// routes/admin.php — Admin Dashboard Route Definitions & Legacy Redirects

return [
    'routes' => [
        '/admin'                => 'Admin\AdminLoginController@index',
        '/admin/dashboard'      => 'Admin\DashboardController@index',
        '/admin/users'          => 'Admin\UsersController@index',
        '/admin/orders'         => 'Admin\OrdersController@index',
        '/admin/add_product'    => 'Admin\ProductsController@add',
        '/admin/edit_product'   => 'Admin\ProductsController@edit',
        '/admin/list_product'   => 'Admin\ProductsController@list',
        '/admin/categories'         => 'Admin\CategoryController@index',
        '/admin/categories/add'     => 'Admin\CategoryController@add',
        '/admin/categories/edit'    => 'Admin\CategoryController@edit',
        '/admin/colors'             => 'Admin\ColorsController@index',
        '/admin/colors/add'         => 'Admin\ColorsController@add',
        '/admin/colors/edit'        => 'Admin\ColorsController@edit',
        '/admin/fragrance'          => 'Admin\FragranceController@index',
        '/admin/fragrance/add'      => 'Admin\FragranceController@add',
        '/admin/fragrance/edit'     => 'Admin\FragranceController@edit',
        '/admin/boxes'              => 'Admin\BoxController@index',
        '/admin/boxes/add'          => 'Admin\BoxController@add',
        '/admin/boxes/edit'         => 'Admin\BoxController@edit',
        '/admin/accessories'        => 'Admin\AccessoriesController@list',
        '/admin/add_accessory'      => 'Admin\AccessoriesController@add',
        '/admin/edit_accessory'     => 'Admin\AccessoriesController@edit',
        '/admin/coupons'            => 'Admin\CouponController@index',
        '/admin/coupons/add'        => 'Admin\CouponController@add',
        '/admin/coupons/edit'       => 'Admin\CouponController@edit',
        '/admin/coupons/delete'     => 'Admin\CouponController@delete',
        '/admin/coupons/toggle'     => 'Admin\CouponController@toggle',
        '/admin/logout'             => 'Admin\AdminLoginController@logout',
    ],
    'redirects' => [
        '/admin_dashboard' => '/admin/dashboard',
        '/users'           => '/admin/users',
        '/orders'          => '/admin/orders',
        '/coupons'         => '/admin/coupons',
        '/add_coupon'      => '/admin/coupons/add',
        '/add_product'     => '/admin/add_product',
        '/edit_product'    => '/admin/edit_product',
        '/list_product'    => '/admin/list_product',
        '/categories'      => '/admin/categories',
        '/fragrance'       => '/admin/fragrance',
        '/boxes'           => '/admin/boxes',
        '/colors'          => '/admin/colors',
        '/sizes'           => '/admin/categories',
        '/add_accessory'   => '/admin/add_accessory',
        '/edit_accessory'  => '/admin/edit_accessory',
        '/list_accessory'  => '/admin/list_accessory',
    ]
];
?>
