<?php
// routes/web.php — Storefront Route Definitions

return [
    '/' => 'Frontend\HomeController@index',
    '/about' => 'Frontend\AboutController@index',
    '/contact' => 'Frontend\ContactController@index',
    '/journal' => 'Frontend\JournalController@index',
    '/shop' => 'Frontend\ShopController@index',
    '/accessories' => 'Frontend\AccessoriesController@index',
    '/builder' => 'Frontend\DesignController@index',
    '/customizer' => 'Frontend\DesignController@index',
    '/design' => 'Frontend\DesignController@index',
    '/checkout' => 'Frontend\CheckoutController@index',
    '/thankyou' => 'Frontend\ThankyouController@index',
    '/privacy' => 'Frontend\PrivacyController@index',
    '/terms' => 'Frontend\TermsController@index',
    '/returns' => 'Frontend\ReturnsController@index',
    '/maintenance' => 'Frontend\MaintenanceController@index',
    '/maintainance' => 'Frontend\MaintenanceController@index',  // Typo fallback alias
    // User Dashboard Dedicated Page Routes & Authentication
    '/dashboard' => 'Frontend\DashboardController@index',
    '/dashboard/home' => 'Frontend\DashboardController@home',
    '/dashboard/profile' => 'Frontend\DashboardController@profile',
    '/dashboard/orders' => 'Frontend\DashboardController@orders',
    '/dashboard/wishlist' => 'Frontend\DashboardController@wishlist',
    '/dashboard/cart' => 'Frontend\DashboardController@cart',
    '/dashboard/addresses' => 'Frontend\DashboardController@addresses',
    '/dashboard/payment-methods' => 'Frontend\DashboardController@paymentMethods',
    '/dashboard/wallet' => 'Frontend\DashboardController@wallet',
    '/dashboard/rewards' => 'Frontend\DashboardController@rewards',
    '/dashboard/reviews' => 'Frontend\DashboardController@reviews',
    '/dashboard/recent-products' => 'Frontend\DashboardController@recentProducts',
    '/dashboard/help' => 'Frontend\DashboardController@help',
    '/dashboard/settings' => 'Frontend\DashboardController@settings',
    '/profile' => 'Frontend\DashboardController@profile',
    '/orders' => 'Frontend\DashboardController@orders',
    '/login' => 'Frontend\AuthController@index',
    '/register' => 'Frontend\AuthController@index',
    '/logout' => 'Frontend\AuthController@logout',
    // Auth & Dashboard API Endpoints
    '/api/auth/login' => 'Frontend\AuthController@login',
    '/api/auth/register' => 'Frontend\AuthController@register',
    '/api/dashboard/update-profile' => 'Frontend\DashboardController@updateProfile',
    '/api/dashboard/change-password' => 'Frontend\DashboardController@changePassword',
    '/api/dashboard/save-address' => 'Frontend\DashboardController@saveAddress',
    '/api/dashboard/delete-address' => 'Frontend\DashboardController@deleteAddress',
    '/api/dashboard/submit-review' => 'Frontend\DashboardController@submitReview',
    '/api/dashboard/reorder' => 'Frontend\DashboardController@reorder',
    '/api/dashboard/cancel-order' => 'Frontend\DashboardController@cancelOrder',
    '/api/dashboard/wishlist' => 'Frontend\DashboardController@toggleWishlist',
    '/api/dashboard/support' => 'Frontend\DashboardController@submitSupport',
    '/sync_cart' => 'Frontend\CartController@sync',
    '/logic/sync_cart.php' => 'Frontend\CartController@sync',
    '/api/stripe/create-checkout-session' => 'Frontend\CheckoutController@createStripeSession',
    '/stripe/create-checkout-session.php' => 'Frontend\CheckoutController@createStripeSession',
    '/api/stripe/webhook' => 'Frontend\CheckoutController@stripeWebhook',
    '/stripe/webhook.php' => 'Frontend\CheckoutController@stripeWebhook',
    '/api/place-order' => 'Frontend\CheckoutController@placeOrder',
    '/logic/place_order.php' => 'Frontend\CheckoutController@placeOrder',
    '/api/search' => 'Frontend\SearchController@search',
    '/search' => 'Frontend\SearchController@search',
    '/api/validate-coupon' => 'Frontend\CouponController@validate',
    '/api/coupon/validate' => 'Frontend\CouponController@validate',
    '/api/shipping/rates' => 'Frontend\ShippingController@calculateRates',
    '/api/fedex/rates' => 'Frontend\ShippingController@calculateRates',
];
?>
